DROP DATABASE IF EXISTS bib;
CREATE DATABASE IF NOT EXISTS bib;

USE bib;

CREATE TABLE Lender(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  Street VARCHAR(255) NOT NULL,
  HouseNumber VARCHAR(50) NOT NULL,
  PostalCode INT NOT NULL,
  City VARCHAR(255) NOT NULL,
  BirthDate DATE NOT NULL,
  Fine DOUBLE NOT NULL DEFAULT 0 CHECK (Fine >= 0)
);

CREATE TABLE Publisher(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL CHECK (Email REGEXP '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
  Telephone VARCHAR(25) NOT NULL CHECK (Telephone REGEXP '^[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{2}$' OR Telephone REGEXP '^[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}$')
);

CREATE TABLE Location(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Floor INT NOT NULL,
  Corridor INT NOT NULL
);

CREATE TABLE Item(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  Category VARCHAR(255) NOT NULL,
  PublisherId INT NOT NULL,
  LocationId INT NOT NULL,
  CONSTRAINT FK_Item_Publisher FOREIGN KEY (PublisherId) REFERENCES Publisher(Id),
  CONSTRAINT FK_Item_Location FOREIGN KEY (LocationId) REFERENCES Location(Id)
);

CREATE TABLE Lender_Item(
  LenderId INT,
  ItemId INT,
  FromDateTime DATETIME,
  ReturnDateTime DATETIME,
  PRIMARY KEY (LenderId, ItemId, FromDateTime),
  CONSTRAINT FK_Lender_Item_Lender FOREIGN KEY (LenderId) REFERENCES Lender(Id) ON DELETE CASCADE,
  CONSTRAINT FK_Lender_Item_Item FOREIGN KEY (ItemId) REFERENCES Item(Id) ON DELETE CASCADE
);

DELIMITER //
CREATE TRIGGER check_return_date
BEFORE INSERT ON Lender_Item
FOR EACH ROW
BEGIN
    IF NEW.ReturnDateTime <= NEW.FromDateTime THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ReturnDateTime must be greater than FromDateTime';
    END IF;
END //
DELIMITER ;
